# Generated by Django 5.2.14 on 2026-05-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='change_likelihood_tomorrow',
            field=models.PositiveSmallIntegerField(default=0, help_text='Estimated probability (0-100%) that the results will change tomorrow.'),
        ),
    ]
